### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Komport** [Educational-MySQL/UDFs-written-in-Python#4]
Hi :)

To avoid below error
`python: can't open file 'factorial.py': [Errno 2] No such file or directory`

I have changed this string with direct path to python file.
`std::string command("python factorial.py");`

after this changes error change as below
```
Traceback (most recent call last):
  File "/usr/lib/mysql/plugin/factorial.py", line 31, in <module>
    main()
  File "/usr/lib/mysql/plugin/factorial.py", line 18, in main
    num = int(num)
ValueError: invalid literal for int() with base 10: '\x01'
```

**Comment by ShahriyarR** [comment]
Thanks for report,
Interesting thing here is that if you call function with 0:
```
select factorial(0);
```
It will give 'Not Enough arguments' error':

```
Not enough arguments
```

**Comment by ShahriyarR** [comment]
Fixed. Closing
